services:
  postgres:
    image: postgres:17
    container_name: govtrackr-db-dev
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: govtrackr_db_dev
      POSTGRES_USER: govtrackr_user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: govtrackr-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data

volumes:
  postgres_data_dev:
  redis_data_dev:
